server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth:
  jwt:
    issuer: http://localhost:8081
    audience: fitness-platform
    access-token-ttl: PT15M
    refresh-token-ttl: P30D
    keys-directory: auth-keys
    key-id: auth-key-1
